name = "cloudflare-docker-proxy-eyark"
compatibility_date = "2023-12-01"


[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env]
YARN_ENABLE_IMMUTABLE_INSTALLS = false

[env.vars]
CUSTOM_DOMAIN = "eyark.com"



[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "eyark.com"


[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.eyark.com", custom_domain = true },
#   { pattern = "quay.eyark.com", custom_domain = true },
#   { pattern = "gcr.eyark.com", custom_domain = true },
#   { pattern = "k8s-gcr.eyark.com", custom_domain = true },
#   { pattern = "k8s.eyark.com", custom_domain = true },
#   { pattern = "ghcr.eyark.com", custom_domain = true },
#   { pattern = "cloudsmith.eyark.com", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.eyark.com", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
